name: Test Backend

on:
  pull_request:
    paths:
      - 'backend/**'
    branches: [ master ]
  push:
    paths:
      - 'backend/**'
    branches: [ master ]
    
env:
  PROJECT_ID: motiongenerator
  SERVICE_NAME: motion-backend
  PYTHON_VERSION: 3.6.9

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/dev.txt

    - name: Download model artifacts
      working-directory: backend
      run: 
        python scripts/download_artifacts.py

    - name: Lint with flake8
      working-directory: backend
      run: |
        flake8 . --count --ignore=E501 --show-source --statistics

    - name: Test with pytest
      working-directory: backend
      run: |
        python -m pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      if: ${{ github.event_name == 'push' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./backend/coverage.xml
        name: backend
