name: Build Backend and Push It to Container Registry

on:
  push:
    paths:
      - 'backend/**'
    branches: [ master ]
    
env:
  PROJECT_ID: motiongenerator
  SERVICE_NAME: motion-backend

jobs:
  # This workflow contains a single job called "build"
  build-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.BUILD_SA_KEY }}
        project_id: motiongenerator

    # Build and push image to Google Container Registry
    - name: Build
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrest.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
