name: Test Backend
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
    branches: [ master ]
    
env:
  NODE_VERSION: 13.x

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: frontend-build 
        path: ./frontend/build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:motiongenerator-development
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_PATH: ./frontend
