name: Test Backend

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
    branches: [ master ]
    
env:
  NODE_VERSION: 13.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name:
      uses: actions/setup-node@master
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      working-directory: frontend
      run: |
        npm install

    - name: Test
      working-directory: frontend
      run: |
        npm run test

    - name: Build
      working-directory: frontend
      run: |
        npm run build

    - name: Archive Production Artifact
      working-directory: frontend
      uses: actions/upload-artifact@master
      with:
        name: frontend-build 
        path: ./frontend/build
