name: Test Model Pipeline

on:
  pull_request:
    paths:
      - 'model/**'
    branches: [ master ]
  push:
    paths:
      - 'model/**'
    branches: [ master ]
    
env:
  PYTHON_VERSION: 3.6.9

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      WANDB_PROJECT: ${{ secrets.WANDB_PROJECT }}
      WANDB_WATCH: ${{ secrets.WANDB_WATCH }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r model/requirements.txt

    - name: Lint with flake8
      working-directory: model
      run: |
        flake8 . --count --ignore=E501 --show-source --statistics

    - name: Test with pytest
      working-directory: model
      run: |
        python -m pytest --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      if: ${{ github.event_name == 'push' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./model/coverage.xml
        flags: model
